slot:
  spins: 500000000
  threadCount: 4
  stake: 1.0
  multiplierMin: 0.1
  multiplierMid1: 100.0
  multiplierMid2: 300.0
  multiplierMid3: 1000.0
  multiplierMax: 3000.0
  crashExponentLow: 1.0
  crashExponentMid: 1.9
  crashExponentUpperMid: 4.0
  crashExponentHigh: 9.0
  zeroSpinInterval: 36

spring:
  thymeleaf:
    cache: false
